version: "2"
services:
  node:
    build: ./app
    volumes:
      - ./app:/src/app
      - ./logs/npm:/home/node/.npm/_logs
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - 31380:3000
    restart: always
  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./docker-configs/postgresql.conf:/etc/postgresql.conf
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    command: postgres -c config_file=/etc/postgresql.conf
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:31300:80
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    command: /bin/bash /entry.sh
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./docker-configs/redis.conf:/etc/redis.conf
      - ./docker-data/redis:/var/lib/redis
    command: redis-server /etc/redis.conf
  phpredmin:
    image: sasanrose/phpredmin
    restart: always
    links:
      - redis:redis
    ports:
      - 127.0.0.1:31301:80
    depends_on:
      - redis
    environment:
      PHPREDMIN_DATABASE_REDIS_0_HOST: redis